### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [s3team/Squirrel#1]
when run `make afl-fuzz`, it report
```
g++: error: unrecognized command line option ‘--std=c++2a’; did you mean ‘--std=c++03’?
make: *** [Makefile:78: afl-fuzz] Error 1
```

**Comment by Changochen** [comment]
I think this requires a newer version of g++, for example, 8.3. We will update with a better build instructions soon. Currently the `README.md` is far from complete.

**Comment by zhouqiang-cl** [comment]
Thank you for your quick reply and fix. I will have a try

**Comment by Changochen** [comment]
We have provided docker files for MySQL, Postgre, and Mariadb. You can try it if interested.
