### ISSUE TITLE
How to construct the generator

### ISSUE THREAD

**Issue by bajinsheng** [s3team/Squirrel#10]
I saw there are specific grammar files for each DBMS, such as: https://github.com/s3team/Squirrel/blob/master/SQLite/parser/bison_parser.y

How do I get the yacc file if I want to test a new DBMS?

**Comment by huhong789** [comment]
For Squirrel, we just constructed the parser for each DBMS manually, like one for SQLite, one for MySQL. If you want to apply to a new DBMS, you need to construct the parser by yourself.

The good news is, we have a follow up work, PolyGlot, which can automatically generate the parser if you can provide the BNF description of the grammar (which is usually available online). The code is also on GitHub https://github.com/s3team/Polyglot.

**Comment by bajinsheng** [comment]
I see. Thanks!
