### ISSUE TITLE
Missing binary sqlite_harness

### ISSUE THREAD

**Issue by taptipalit** [s3team/Squirrel#19]
Hi, 

I'm trying to fuzz sqlite with Squirrel. The README tells me to run

`afl-fuzz -i input -o output -- sqlite_harness`

But I don't find any sqlite_harness binary in the repo. 
Also, which directory should I run the above `afl-fuzz` command?

**Comment by Changochen** [comment]
Hi, the new version of `Squirrel` is based on `AFLplusplus`. This is a beta version and the document is far from perfect, but we are working to make it better.

For your problem, you should compile `aflplusplus` to get the afl-fuzz. For `input`, you can either use `https://github.com/s3team/Squirrel/tree/master/data/fuzz_root/input` or collect your own. 

You should also build your own `sqlite_harness`. One way to do so is (from oss-fuzz)
```
# Set CC and CXX to afl-cc and afl-c++
cd $SRC/sqlite # clone the official sqlite repo
export CFLAGS="$CFLAGS -DSQLITE_MAX_LENGTH=128000000 \
               -DSQLITE_MAX_SQL_LENGTH=128000000 \
               -DSQLITE_MAX_MEMORY=25000000 \
               -DSQLITE_PRINTF_PRECISION_LIMIT=1048576 \
               -DSQLITE_DEBUG=1 \
               -DSQLITE_MAX_PAGE_COUNT=16384"             
               
./configure
make clean
make -j$(nproc)
make sqlite3.c

$CC $CFLAGS -I. -c \
    $SRC/sqlite3/test/ossfuzz.c -o $SRC/sqlite3/test/ossfuzz.o

# 
$CXX $CXXFLAGS \
    $SRC/sqlite3/test/ossfuzz.o -o $OUT/ossfuzz \
    /path/to/aflplusplus/libAFLDriver.a  ./sqlite3.o -ldl -pthread
```

**Comment by taptipalit** [comment]
Thanks for the quick response, and thanks for updating to AFLplusplus! 

Just so I understand, the `sqlite_harness` is the same binary as the `sqlite3` binary I get when I compile SQLite from the source?
