### ISSUE TITLE
run.sh move to root?

### ISSUE THREAD

**Issue by mariadb-RoelVandePaar** [s3team/Squirrel#24]
`run.sh` is currently in `./data`, however it's directory references all point to being in the root rather than in `./data` so propose moving `run.sh` to the root of the Squirrel repo. It will also be easier to find it there.

**Comment by mariadb-RoelVandePaar** [comment]
One other small suggestion is to use `$(pwd)` instead of `\`pwd\`` in the script as the latter is more error prone and somewhat outdated

**Comment by mariadb-RoelVandePaar** [comment]
One more idea is to make `run.sh` more universal, i.e. to have clear sections for each DB and an easy way to enable/disable sections. Perhaps best something like
```
DB_OPTION=x    # 1=MariaDB, 2=MySQL etc.
if [ "${DB_OPTION}" -eq 1 ]; then
   export AFL....
   export...
   ...
   ./AFLplusplus/afl-fuzz/afl-fuzz ...
elif [ "${DB_OPTION}" -eq 2 ]; then
   export AFL....
   export...
   ...
   ./AFLplusplus/afl-fuzz/afl-fuzz ...
fi
```

**Comment by Changochen** [comment]
We provided dockerfiles to run. Please take a look at the updated readme!
