### ISSUE TITLE
Possible improvement for custom mutator

### ISSUE THREAD

**Issue by mariadb-RoelVandePaar** [s3team/Squirrel#25]
Impressive work so far guys :) Have not got it running yet, but close

Possible improvement opportunity for the new custom mutator:
```
[*] Custom mutator does not implement all three trim APIs, standard trimming will be used.
```

Some other potential opportunities:
```
[*] optional symbol 'afl_custom_init_trim' not found.
[*] optional symbol 'afl_custom_trim' not found.
[*] optional symbol 'afl_custom_post_trim' not found.
[*] optional symbol 'afl_custom_havoc_mutation' not found.
[*] optional symbol 'afl_custom_havoc_mutation_probability' not found.
```
Seen during `afl-fuzz` startup

**Comment by Changochen** [comment]
These symbols are optional and will not affect anything.

**Comment by mariadb-RoelVandePaar** [comment]
I know they are optional. But are you sure that implementing them will have no effect?
