### ISSUE TITLE
Some sql cannot be parsered. afl_custom_fuzz_count return 0

### ISSUE THREAD

**Issue by LimbicSys** [s3team/Squirrel#40]
I have some sql testcases. But it seems that they cannot be parsed by `parser` function in `srcs/internal/postgresql/srcs/utils.cpp`. Thus, `afl_custom_fuzz_count` return 0.
For example, a simple statement:
``` sql
select a as b from c;
```

I have wrote a simple tool to call the `parser` function with a given sql statement to figure out which one is *invalid*. But it cannot tell me why a statement is invalid. This problem make me can't use some testcases from somewhere directly and I even don't kown how to *fix* them to make them work with Squirrel.

By the way, how to extend the parser to support more sql syntax for a specific database?

**Comment by Changochen** [comment]
You can check the bison and flex files for each database (for your case, https://github.com/s3team/Squirrel/blob/master/srcs/internal/postgresql/parser/bison.y) and see whether the current grammar supports your sql. Similarly, if you want to extend the parser, you can modify the bison file and compile them.
