### ISSUE TITLE
If I want to apply Squirrel to other DBMS, how should we go about it?

### ISSUE THREAD

**Issue by ash2kzzz** [s3team/Squirrel#41]
I am a student and currently have an interest to detect vulnerabilities in a Chinese database, and I happened to see this article on Squirrel, so I want to use Squirrel to test it.
However, I found that currently Squirrel only supports four databases such as mysql. If I want to apply Squirrel to this DBMS, how should I go about it?

**Comment by Changochen** [comment]
You should implement a parser (https://github.com/s3team/Squirrel/blob/master/srcs/internal/mysql/parser/bison.y and https://github.com/s3team/Squirrel/blob/master/srcs/internal/mysql/parser/flex.l) and the ast related code (https://github.com/s3team/Squirrel/blob/master/srcs/internal/mysql/srcs/ast.cpp). The mutator can be reused.
