### ISSUE TITLE
When Squirrel is applied on a distributed database, like OceanBase

### ISSUE THREAD

**Issue by wayyoungboy** [s3team/Squirrel#42]
When Squirrel is applied to multiple processes, it will have an impact on stability and collected branch nodes. Is this likely to lead to inaccurate collection coverage？

Is there a solution that can support this type of database？

**Comment by Changochen** [comment]
>  Is this likely to lead to inaccurate collection coverage？

Yes. This is a known problem for fuzzing.

> Is there a solution that can support this type of database？

I suggest you try the following ways:
1. Try the threadsafe instrumentation of aflpp (https://github.com/AFLplusplus/AFLplusplus/blob/7101192865893e00b9029d0cb898a3ca3015d50b/include/envs.h#L158).
2. Try to reduce the random sources in the database.
3. Make the execution of each query synchronous. The stability of fuzzing MySQL/Postgres is only about 40-50% (without trying to improve the stability).

**Comment by wayyoungboy** [comment]
we tested oceanbase by Squirrel. And the stability is only about 35%.

**Comment by Changochen** [comment]
It should be database-dependent. 

> When Squirrel is applied to multiple processes

By the way, are these processes all from a single database server? Or you run multiple fuzzing instance in the same enviroment?

**Comment by wayyoungboy** [comment]
all processes from a single database server.

may I can provide some code to Squirrel to enable it to be applied in OceanBase, like applied in Mysql.

**Comment by Changochen** [comment]
>  all processes from a single database server.

I see. Then the instability should be from OceanBase. 
> 
> 
> may I can provide some code to Squirrel to enable it to be applied in OceanBase, like applied in Mysql.

Sure. You are welcome to contribute to Squirrel!
