### ISSUE TITLE
Floating point exception occurs when testing sqlite with inputs in github

### ISSUE THREAD

**Issue by youngjooko** [s3team/Squirrel#5]
Hello.

I run the Squirrel using SQLite.
But before testing the SQLite the fuzzer has Floating point exception.

I run the command "./afl-fuzz -n -i ./input/ -o output/ -- ~/server_fuzz/sqlite/bld/sqlite3 --bail"
The input directory includes the input file of 1.txt in "Squirrel/SQLite/fuzz_root/1.txt"

I have searched the point that generates Floating point exception.
When the fuzzer executes "fuzz_one() -> calling g_mutator.mutate_all(ir_set) -> mutate(ir) -> strategy_insert(input)", the exception occurs.
But, I couldn't find exact reason and I wonder that  you have ever encountered this issue before? 
If not, can you tell me why I am getting these exceptions?

I tested on Ubuntu 16.04.7 LTS.

![fpe](https://user-images.githubusercontent.com/53934679/105358427-7de54200-5c39-11eb-9a10-f5c15b19aa12.PNG)

**Comment by Jqqzzz** [comment]
hey, I met the same problem with you. 
Can you share with me how did you solve this problem?
Thank you.

**Comment by youngjooko** [comment]
Hello,

In my case, when I run the fuzzer without  a "pragam" file and a init_lib file, the except occured.
So, I added the pragma and init_lib.
________________________________
보낸 사람: Jqqzzz ***@***.***>
보낸 날짜: 2022년 6월 29일 수요일 오전 11:45
받는 사람: s3team/Squirrel ***@***.***>
참조: 고영주(컴퓨터공학과) ***@***.***>; State change ***@***.***>
제목: Re: [s3team/Squirrel] Floating point exception occurs when testing sqlite with inputs in github (#5)


hey, I met the same problem with you.
Can you share with me how did you solve this problem?
Thank you.
