### ISSUE TITLE
What is this "aaa" in the python file?

### ISSUE THREAD

**Issue by zhangysh1995** [s3team/Squirrel#7]
https://github.com/s3team/Squirrel/blob/0c119788901bfa17a15db491fe67bb57dab822b9/MySQL/docker/run.py#L25

**Comment by mariadb-RoelVandePaar** [comment]
A fictive name given to the instance. It can be anything. This is because AFL normally expects the binary to be fuzzed here, but in the case of Squirrel a shared memory space is used (ref ticket #9 for some more info).

**Comment by Changochen** [comment]
Thanks for the answer, @mariadb-RoelVandePaar!
